In [1]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print ('A+B = ',np.add(A,B))
print ('A-B = ',np.subtract(A,B))

A+B =  [5 5 3]
A-B =  [-3 -1  3]


In [2]:
A = np.array([1,2,3])
print ('np.multiply(A,A) = ',np.multiply(A,A))
print ('A * A = ',A*A)

np.multiply(A,A) =  [1 4 9]
A * A =  [1 4 9]


In [4]:
C = np.array([[1,2,3],
              [1,1,1]])
D = np.array([[4,3,9,9],
             [1,1,2,2],
             [4,2,1,1]])

print ('np.matmul(C,D) = ',np.matmul(C,D))
print ('C@D=',np.matmul(C,D))

np.matmul(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
C@D= [[18 11 16 16]
 [ 9  6 12 12]]


In [5]:
C@D

array([[18, 11, 16, 16],
       [ 9,  6, 12, 12]])

In [7]:
A*C

array([[1, 4, 9],
       [1, 2, 3]])

In [8]:
m_4_4 = np.array([[1,2,3,4],                  
                 [3,6,2,3],
                 [4,2,1,5],
                 [6,4,4,2]])
m_3_4_2 = np.array([
                        [[2,3],
                         [6,3],
                         [1,3],
                         [9,4]],
    
                        [[2,3],
                         [6,1],
                         [2,1],
                         [3,2]],
    
                        [[7,4],
                         [2,7],
                         [4,7],
                         [9,5]]
])
print (m_4_4.shape)
print (m_3_4_2.shape)

(4, 4)
(3, 4, 2)


In [11]:
print ('dot:\n',np.dot(m_4_4,m_3_4_2))
print ('matmul:\n',np.matmul(m_4_4,m_3_4_2))
print (np.dot(m_4_4,m_3_4_2).shape)
print (np.matmul(m_4_4,m_3_4_2).shape)

dot:
 [[[53 34]
  [32 16]
  [59 59]]

 [[71 45]
  [55 23]
  [68 83]]

 [[66 41]
  [37 25]
  [81 62]]

 [[58 50]
  [50 30]
  [84 90]]]
matmul:
 [[[53 34]
  [71 45]
  [66 41]
  [58 50]]

 [[32 16]
  [55 23]
  [37 25]
  [50 30]]

 [[59 59]
  [68 83]
  [81 62]
  [84 90]]]
(4, 3, 2)
(3, 4, 2)
